services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src:cached
      - node_modules:/usr/src/node_modules
    ports:
      - "5173:5173"

volumes:
  node_modules:
